In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

import astropy.units as u
import astropy.coordinates as coord
from astropy.table import Table

import gapipes as gp

In [2]:
from galpy.potential import MWPotential2014, MiyamotoNagaiPotential
from galpy.util import bovy_conversion

In [3]:
MWPotential2014

In [2]:
mp= MiyamotoNagaiPotential(a=0.5,b=0.0375,normalize=1.)
mp(1.,0.)

-1.2889062500000001

In [30]:
p0 = MWPotential2014[1]

In [38]:
p0._a, p0._b, p0._ro, p0._vo, p0._amp

(0.375, 0.035, 8.0, 220.0, 0.7574802019371595)

Galpy uses left-handed coordinate system:
- x away from galactic center
- y in galactic rotational direction
- z to north of galactic plane

In [19]:
for p in MWPotential2014:
    print(p.ttensor(8.3/8, 0.10/8))
    print(p.ttensor(8.3/8, 0.10/8,eigenval=True))

[[ 0.08950485 -0.          0.00161767]
 [-0.         -0.04476217 -0.        ]
 [ 0.00161767 -0.         -0.04474268]]
[ 0.08952434 -0.04476217 -0.04476217]
[[ 0.86623269 -0.          0.18848691]
 [-0.         -0.54443309 -0.        ]
 [ 0.18848691 -0.         -5.39120516]]
[ 0.87190516 -5.39687763 -0.54443309]
[[ 0.15625692 -0.          0.00587758]
 [-0.         -0.33158201 -0.        ]
 [ 0.00587758 -0.         -0.33151119]]
[ 0.15632773 -0.33158201 -0.33158201]


In [5]:
from functools import reduce
ttensor_sum = reduce(np.add, [p.ttensor(8.3/8, 0.10/8) for p in MWPotential2014])

In [16]:
list(map(lambda x: (x._vo, x._ro), MWPotential2014))

[(220.0, 8.0), (220.0, 8.0), (220.0, 8.0)]

In [24]:
timeunit = (bovy_conversion.time_in_Gyr(220, 8)*u.Gyr).to(u.Myr)

In [18]:
np.sqrt(1/np.abs(ttensor_sum[0,0]))*timeunit.to(u.Myr)

<Quantity 33.71805959 Myr>

In [35]:
ttensors = [p.ttensor(8.3/8, 0.10/8) for p in MWPotential2014]

print(np.abs(ttensors[0])<=np.abs(ttensors[1]))
print(np.abs(ttensors[2])<=np.abs(ttensors[1]))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [38]:
ttensors[1]

array([[ 0.86623269, -0.        ,  0.18848691],
       [-0.        , -0.54443309, -0.        ],
       [ 0.18848691, -0.        , -5.39120516]])

In [45]:
np.sqrt(1/ttensors[1][0,0])*timeunit,np.sqrt(1/ttensors[1][0,2])*timeunit

(<Quantity 38.20292365 Myr>, <Quantity 81.89799931 Myr>)

In [44]:
np.sqrt(1/np.abs(ttensors[1][[0,1,2],[0,1,2]]))*timeunit

<Quantity [38.20292365, 48.18830245, 15.3133763 ] Myr>

In [41]:
(1./(37*u.km/u.s/u.kpc)).to(u.Myr)

<Quantity 26.4268168 Myr>

In [128]:
tcross = 5 *u.pc / (0.3 * u.km/u.s)
print(tcross.to(u.Myr))
N = 400
trelax = (0.1 * N / np.log(N) * tcross).to(u.Myr)
print(trelax)

16.296537027885474 Myr
108.79835405686674 Myr
