In [1]:
import numpy as np
import astropy.units as u
from gala.potential import MiyamotoNagaiPotential

ModuleNotFoundError: No module named 'gala'

In [42]:
import gala.potential as gp
import gala.dynamics as gd

In [41]:
potential = gp.MilkyWayPotential()

In [43]:
w0 = gd.PhaseSpacePosition([8,0,-.016]*u.kpc, vel=[0,220,-1.18]*u.km/u.s)

In [44]:
orbit = potential.integrate_orbit(w0, dt=-0.5*u.Myr, n_steps=10000)

/home/soh/.conda/envs/matrix/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/soh/.conda/envs/matrix/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)


In [48]:
%matplotlib inline
import matplotlib.pyplot as plt

In [51]:
orbit.z.max()

<Quantity 0.02244393 kpc>

In [52]:
 from gala.potential import MilkyWayPotential
pot = MilkyWayPotential(halo=dict(c=1.)) # make it spherical
a=pot.hessian([8, 0., .1] * u.kpc)[[0,1,2],[0,1,2],0]

In [53]:
a

<Quantity [-0.00071675,  0.00044477,  0.00464677] 1 / Myr2>

In [59]:
(1*u.pc/(.3*u.km/u.s)).to(u.Myr)

<Quantity 3.25930741 Myr>

In [57]:
1./np.sqrt(np.abs(a))

<Quantity [37.3523065 , 47.41692058, 14.66980698] Myr>

In [54]:
-np.sign(a) * np.sqrt(np.abs(a)).to(u.m/u.s/u.pc)

<Quantity [ 26.17755939, -20.62116666, -66.65338018] m / (pc s)>

In [13]:
print(MiyamotoNagaiPotential(1, a=0.5,b=0.0375).hessian([1,0,0])[:,:,0])

[[-9.07236430e-001  0.00000000e+000 -9.04140132e-322]
 [ 0.00000000e+000  6.83389034e-001  0.00000000e+000]
 [-9.04140132e-322  0.00000000e+000  9.79524282e+000]]


Init signature: MiyamotoNagaiPotential(m, a, b, units=None, origin=None, R=None)
Docstring:     
MiyamotoNagaiPotential(m, a, b, units=None, origin=None, R=None)

Miyamoto-Nagai potential for a flattened mass distribution.

See: http://adsabs.harvard.edu/abs/1975PASJ...27..533M

Parameters
----------
m : :class:`~astropy.units.Quantity`, numeric [mass]
    Mass.
a : :class:`~astropy.units.Quantity`, numeric [length]
    Scale length.
b : :class:`~astropy.units.Quantity`, numeric [length]
    Scare height.
units : `~gala.units.UnitSystem` (optional)
    Set of non-reducable units that specify (at minimum) the
    length, mass, time, and angle units.
origin : `~astropy.units.Quantity` (optional)
    The origin of the potential, the default being 0.
R : `~scipy.spatial.transform.Rotation`, array_like (optional)
    A Scipy ``Rotation`` object or an array representing a rotation matrix
    that specifies a rotation of the potential. This is applied *after* the
    origin shift. Default is 